package org.rogach.jopenvoronoi.geometry;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.rogach.jopenvoronoi.HalfEdgeDiagram;
import org.rogach.jopenvoronoi.site.Site;
import org.rogach.jopenvoronoi.vertex.Vertex;

/**
 * Face in the half-edge Voronoi diagram.
 * <p>
 * A face stores one representative half-edge plus metadata about the generating
 * site and whether the face is a null/helper face used internally by the line-site
 * insertion algorithm.
 */
public class Face {

	private Edge edge;
	private Site site;
	private FaceStatus status;
	private boolean is_null_face;
	private HalfEdgeDiagram diagram;
	public int diagramIndex = -1;

	public Face() {
	}

	/** Returns the representative/starting edge of this face. */
	public Edge getEdge() {
		return edge;
	}

	/** Sets the representative/starting edge of this face. */
	public void setEdge(Edge edge) {
		this.edge = edge;
	}

	/**
	 * Returns the half-edges reached by walking this face from {@link #getEdge()}
	 * via successive {@link Edge#next} links.
	 * <p>
	 * The returned list reflects the underlying half-edge structure, so it can
	 * include internal/helper edges and not only user-visible Voronoi boundary
	 * edges. In particular, callers may see edge types such as
	 * {@link EdgeType#NULLEDGE}.
	 */
	public List<Edge> getEdges() {
		return requireDiagram().faceEdges(this);
	}

	/** Returns the vertices encountered while traversing {@link #getEdges()}. */
	public List<Vertex> getVertices() {
		return requireDiagram().faceVertices(this);
	}

	/**
	 * Returns the distinct neighboring faces reached through the twin of each edge
	 * in {@link #getEdges()}.
	 */
	public List<Face> getAdjacentFaces() {
		Set<Face> adjacentFaces = new LinkedHashSet<>();
		for (Edge boundaryEdge : getEdges()) {
			if (boundaryEdge.twin != null && boundaryEdge.twin.face != null && boundaryEdge.twin.face != this) {
				adjacentFaces.add(boundaryEdge.twin.face);
			}
		}
		return new ArrayList<>(adjacentFaces);
	}
	
	/**
	 * Returns true if this face is a point-site cell that corresponds to a polygon
	 * vertex, i.e. it is adjacent to at least two distinct line-site faces whose
	 * segments share this point as an endpoint.
	 */
	public boolean isPolygonVertexCell() {
		if (is_null_face || site == null || !site.isPoint())
			return false;

		Point v = site.position();
		Set<Long> segments = new HashSet<>();

		for (Face adj : getAdjacentFaces()) {
			if (adj == null || adj.is_null_face || adj.site == null || !adj.site.isLine()) continue;

			Point a = adj.site.start();
			Point b = adj.site.end();

			if (a == v || b == v) {
				int ha = System.identityHashCode(a);
				int hb = System.identityHashCode(b);
				long key = (ha < hb)
					? (((long) ha) << 32) ^ (hb & 0xffffffffL)
					: (((long) hb) << 32) ^ (ha & 0xffffffffL);
				segments.add(key);
			}
		}

		return segments.size() >= 2;
	}

	/** Returns the site that generates this face, if any. */
	public Site getSite() {
		return site;
	}

	/** Sets the generator site for this face. */
	public void setSite(Site site) {
		this.site = site;
	}

	public FaceStatus getStatus() {
		return status;
	}

	/** Sets the status of this face. */
	public void setStatus(FaceStatus status) {
		this.status = status;
	}

	/**
	 * Returns whether this face is an internal helper face rather than a
	 * user-visible Voronoi cell.
	 * <p>
	 * Null faces are introduced by the line-site insertion algorithm to model
	 * endpoint/null-edge structure in the half-edge graph.
	 */
	public boolean isNullFace() {
		return is_null_face;
	}

	/** Sets whether this face is a null face. */
	public void setNullFace(boolean isNullFace) {
		this.is_null_face = isNullFace;
	}

	/** Returns whether this face is generated by a point site. */
	public boolean isPointSiteFace() {
		return site != null && site.isPoint();
	}

	/** Returns whether this face is generated by a line site. */
	public boolean isLineSiteFace() {
		return site != null && site.isLine();
	}

	/** Returns whether this face is generated by an arc site. */
	public boolean isArcSiteFace() {
		return site != null && site.isArc();
	}

	/** Attaches this face to the half-edge diagram that owns it. */
	public void attachDiagram(HalfEdgeDiagram diagram) {
		this.diagram = diagram;
	}

	private HalfEdgeDiagram requireDiagram() {
		if (diagram == null) {
			throw new IllegalStateException("Face is not attached to a diagram");
		}
		return diagram;
	}

	@Override
	public String toString() {
		var sb = new StringBuilder();
		sb.append("F(");
		var current = edge;
		var c = 0;
		do {
			if (current == null) {
				break;
			}
			sb.append(current.source.position);
			sb.append(">");
			current = current.next;
			c++;
		} while (current != edge && c < 100);
		if (c >= 100) {
			sb.append("...");
		}
		sb.append(")");
		return sb.toString();
	}
}
