package org.rogach.jopenvoronoi.jts;

import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.List;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.CoordinateList;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.geom.MultiLineString;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.geom.Polygonal;
import org.locationtech.jts.operation.linemerge.LineMerger;
import org.locationtech.jts.operation.polygonize.Polygonizer;
import org.rogach.jopenvoronoi.VoronoiDiagram;
import org.rogach.jopenvoronoi.filter.MedialAxisFilter;
import org.rogach.jopenvoronoi.filter.PolygonInteriorFilter;
import org.rogach.jopenvoronoi.geometry.Edge;
import org.rogach.jopenvoronoi.geometry.EdgeType;
import org.rogach.jopenvoronoi.geometry.Face;

/**
 * High-level JTS view of the segment Voronoi diagram of a polygonal geometry.
 * <p>
 * Wraps a {@link VoronoiDiagram} built from a JTS {@link Polygon} or
 * {@link org.locationtech.jts.geom.MultiPolygon} and exposes the common derived
 * products directly as JTS geometries:
 * <ul>
 * <li>{@link #getCells()} — every Voronoi cell in the diagram</li>
 * <li>{@link #getInteriorCells()} — only the cells generated by the polygon
 * interior</li>
 * <li>{@link #getMedialAxis()} — the interior medial axis, dissolved into
 * maximal linestrings</li>
 * <li>{@link #getMedialAxisCoverage()} — the polygonal coverage obtained by
 * cutting the input polygon along its medial axis</li>
 * </ul>
 * Curved (parabolic) Voronoi edges are approximated by adaptively sampled
 * chords whose deviation from the true curve never exceeds the configured
 * tolerance.
 * <p>
 * This object owns the filter state ({@code valid} flags) of its underlying
 * diagram: medial-axis queries reset and re-apply edge filters on each call.
 * If you access {@link #getVoronoiDiagram()} directly and apply your own
 * filters, subsequent medial-axis queries will clear them.
 */
public final class JtsVoronoi {

	/**
	 * Interior-side convention matching the ring orientations produced by
	 * {@link Geometry#norm()}, which {@link JtsGeometryIO} applies to every
	 * polygon before inserting its sites: shells clockwise, holes
	 * counter-clockwise, so the interior lies to the right of each inserted
	 * boundary segment.
	 */
	private static final boolean INTERIOR_ON_LEFT = false;

	/** Fraction of the input envelope diagonal used as the default sampling tolerance. */
	private static final double DEFAULT_DEVIATION_FRACTION = 1e-3;

	private final Geometry source;
	private final GeometryFactory factory;
	private final double maxDeviation;
	private final VoronoiDiagram diagram;
	private final PolygonInteriorFilter interiorClassifier;

	/**
	 * Builds the Voronoi diagram of the given polygonal geometry with a default
	 * geometry factory and sampling tolerance.
	 * <p>
	 * The default tolerance is {@code 1e-3} of the input envelope diagonal.
	 *
	 * @param polygonal a non-empty {@link Polygon} or
	 *                  {@link org.locationtech.jts.geom.MultiPolygon}
	 */
	public JtsVoronoi(Geometry polygonal) {
		this(polygonal, defaultFactory(polygonal), defaultDeviation(polygonal));
	}

	/**
	 * Builds the Voronoi diagram of the given polygonal geometry.
	 *
	 * @param polygonal    a non-empty {@link Polygon} or
	 *                     {@link org.locationtech.jts.geom.MultiPolygon}
	 * @param factory      factory used to build all returned geometries
	 * @param maxDeviation maximum distance the chord approximation of a curved
	 *                     Voronoi edge may deviate from the true curve; must be
	 *                     positive
	 */
	public JtsVoronoi(Geometry polygonal, GeometryFactory factory, double maxDeviation) {
		if (polygonal == null) {
			throw new IllegalArgumentException("Geometry cannot be null.");
		}
		if (!(polygonal instanceof Polygonal)) {
			throw new IllegalArgumentException("Geometry must be a Polygon or MultiPolygon, got: " + polygonal.getGeometryType());
		}
		if (polygonal.isEmpty()) {
			throw new IllegalArgumentException("Geometry cannot be empty.");
		}
		if (factory == null) {
			throw new IllegalArgumentException("GeometryFactory cannot be null.");
		}
		if (!(maxDeviation > 0)) {
			throw new IllegalArgumentException("maxDeviation must be positive, got " + maxDeviation);
		}
		this.source = polygonal;
		this.factory = factory;
		this.maxDeviation = maxDeviation;
		this.diagram = JtsGeometryIO.toVoronoiDiagram(polygonal);
		this.interiorClassifier = new PolygonInteriorFilter(INTERIOR_ON_LEFT);
		this.interiorClassifier.setGraph(diagram.getDiagram());
	}

	private static GeometryFactory defaultFactory(Geometry polygonal) {
		return polygonal == null ? new GeometryFactory() : polygonal.getFactory();
	}

	private static double defaultDeviation(Geometry polygonal) {
		if (polygonal == null || polygonal.isEmpty()) {
			return 1e-6;
		}
		Envelope env = polygonal.getEnvelopeInternal();
		double diagonal = Math.hypot(env.getWidth(), env.getHeight());
		return Math.max(diagonal * DEFAULT_DEVIATION_FRACTION, 1e-12);
	}

	/** Returns the input geometry this diagram was built from. */
	public Geometry getSource() {
		return source;
	}

	/** Returns the underlying Voronoi diagram for lower-level access. */
	public VoronoiDiagram getVoronoiDiagram() {
		return diagram;
	}

	// -------------------------------------------------------------------------
	// Cells
	// -------------------------------------------------------------------------

	/**
	 * Returns every Voronoi cell in the diagram as a polygon, including the cells
	 * of the polygon exterior (which extend to the diagram's far boundary).
	 * Degenerate faces that do not span a ring are skipped.
	 */
	public List<Polygon> getCells() {
		return facesToPolygons(diagram.getFaces());
	}

	/**
	 * Returns the Voronoi cells generated by the polygon interior: the cells of
	 * interior line-site faces and of point-site faces adjacent to them.
	 * <p>
	 * Cell classification is per face, so the point-site cells at convex polygon
	 * corners are included whole even though they straddle the boundary. Intersect
	 * the result with {@link #getSource()} for cells clipped exactly to the input.
	 */
	public List<Polygon> getInteriorCells() {
		List<Face> interior = new ArrayList<>();
		for (Face face : diagram.getFaces()) {
			if (interiorClassifier.isInterior(face)) {
				interior.add(face);
			}
		}
		return facesToPolygons(interior);
	}

	private List<Polygon> facesToPolygons(List<Face> faces) {
		List<Polygon> polygons = new ArrayList<>(faces.size());
		for (Face face : faces) {
			Polygon polygon = toPolygon(face);
			if (polygon != null) {
				polygons.add(polygon);
			}
		}
		return polygons;
	}

	/**
	 * Converts a face to a polygon by walking its half-edge loop and sampling each
	 * edge. Returns {@code null} for degenerate faces.
	 */
	private Polygon toPolygon(Face face) {
		CoordinateList ring = new CoordinateList();
		for (Edge edge : face.getEdges()) {
			if (edge.source == null || edge.target == null) {
				return null;
			}
			for (org.rogach.jopenvoronoi.geometry.Point p : edge.samplePoints(maxDeviation)) {
				ring.add(new Coordinate(p.x, p.y), false);
			}
		}
		ring.closeRing();
		if (ring.size() < 4) {
			return null;
		}
		return factory.createPolygon(ring.toCoordinateArray());
	}

	// -------------------------------------------------------------------------
	// Medial axis
	// -------------------------------------------------------------------------

	/**
	 * Returns the full interior medial axis, dissolved into maximal linestrings.
	 * <p>
	 * The result includes the branches that reach into every convex polygon
	 * corner, which is the mathematically exact medial axis but is often noisy for
	 * downstream use; see {@link #getMedialAxis(double)} to prune low-salience
	 * branches.
	 */
	public MultiLineString getMedialAxis() {
		return dissolve(medialAxisLines(Double.NaN));
	}

	/**
	 * Returns the interior medial axis pruned with a
	 * {@link MedialAxisFilter} of the given aggressiveness, dissolved into maximal
	 * linestrings.
	 *
	 * @param aggressiveness pruning aggressiveness in {@code [0,1]}; {@code 0}
	 *                       keeps the full medial axis, {@code 1} prunes maximally
	 */
	public MultiLineString getMedialAxis(double aggressiveness) {
		return dissolve(medialAxisLines(aggressiveness));
	}

	/**
	 * Returns the polygonal coverage obtained by cutting the input polygon along
	 * its full medial axis: every returned polygon is bounded by boundary segments
	 * and medial-axis branches, and together they exactly tile the input.
	 */
	public List<Polygon> getMedialAxisCoverage() {
		return polygonize(medialAxisLines(Double.NaN));
	}

	/**
	 * Returns the polygonal coverage obtained by cutting the input polygon along
	 * its medial axis pruned at the given aggressiveness; see
	 * {@link #getMedialAxis(double)}.
	 *
	 * @param aggressiveness pruning aggressiveness in {@code [0,1]}; {@code 0}
	 *                       keeps the full medial axis, {@code 1} prunes maximally
	 */
	public List<Polygon> getMedialAxisCoverage(double aggressiveness) {
		return polygonize(medialAxisLines(aggressiveness));
	}

	/**
	 * Collects the interior medial-axis edges as sampled linestrings, resetting
	 * and re-applying the diagram's edge filters.
	 *
	 * @param aggressiveness {@link MedialAxisFilter} aggressiveness, or
	 *                       {@link Double#NaN} for the unpruned axis
	 */
	private List<LineString> medialAxisLines(double aggressiveness) {
		diagram.filterReset();
		diagram.filter(new PolygonInteriorFilter(INTERIOR_ON_LEFT));
		if (!Double.isNaN(aggressiveness)) {
			diagram.filter(new MedialAxisFilter(aggressiveness));
		}

		List<LineString> lines = new ArrayList<>();
		IdentityHashMap<Edge, Boolean> seenBases = new IdentityHashMap<>();
		for (Edge edge : diagram.getDiagram().edges) {
			if (!isMedialAxisEdge(edge)) {
				continue;
			}
			if (edge.base != null && seenBases.put(edge.base, Boolean.TRUE) != null) {
				continue;
			}
			LineString line = toLineString(edge);
			if (line != null) {
				lines.add(line);
			}
		}
		return lines;
	}

	private static boolean isMedialAxisEdge(Edge edge) {
		return edge != null && edge.valid && edge.source != null && edge.target != null //
				&& edge.type != EdgeType.LINESITE //
				&& edge.type != EdgeType.NULLEDGE //
				&& edge.type != EdgeType.OUTEDGE //
				&& edge.type != EdgeType.SEPARATOR;
	}

	/** Samples an edge into a linestring; returns {@code null} if degenerate. */
	private LineString toLineString(Edge edge) {
		CoordinateList coordinates = new CoordinateList();
		for (org.rogach.jopenvoronoi.geometry.Point p : edge.samplePoints(maxDeviation)) {
			coordinates.add(new Coordinate(p.x, p.y), false);
		}
		if (coordinates.size() < 2) {
			return null;
		}
		return factory.createLineString(coordinates.toCoordinateArray());
	}

	/** Merges edge chains at degree-2 nodes into maximal linestrings. */
	private MultiLineString dissolve(List<LineString> lines) {
		LineMerger merger = new LineMerger();
		merger.add(lines);
		@SuppressWarnings("unchecked")
		Collection<LineString> merged = merger.getMergedLineStrings();
		return factory.createMultiLineString(merged.toArray(new LineString[0]));
	}

	/**
	 * Polygonizes the medial-axis lines together with the polygon boundary.
	 * <p>
	 * The boundary linework is taken from the diagram's own line-site edges rather
	 * than from the input geometry, so its coordinates coincide exactly with the
	 * medial-axis branch tips (both are diagram vertex positions) and the
	 * collection is already correctly noded for the polygonizer.
	 */
	private List<Polygon> polygonize(List<LineString> axisLines) {
		Polygonizer polygonizer = new Polygonizer();
		polygonizer.add(axisLines);
		polygonizer.add(boundaryLines());
		@SuppressWarnings("unchecked")
		Collection<Polygon> polygons = polygonizer.getPolygons();
		return new ArrayList<>(polygons);
	}

	/** Returns the inserted boundary segments as linestrings, one per site. */
	private List<LineString> boundaryLines() {
		List<LineString> lines = new ArrayList<>();
		IdentityHashMap<Edge, Boolean> seenBases = new IdentityHashMap<>();
		for (Edge edge : diagram.getDiagram().edges) {
			if (edge == null || edge.type != EdgeType.LINESITE || edge.source == null || edge.target == null) {
				continue;
			}
			if (edge.base != null && seenBases.put(edge.base, Boolean.TRUE) != null) {
				continue;
			}
			lines.add(factory.createLineString(new Coordinate[] { //
					JtsGeometryIO.toCoordinate(edge.source.position), //
					JtsGeometryIO.toCoordinate(edge.target.position) }));
		}
		return lines;
	}
}
