package org.rogach.jopenvoronoi.jts;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.locationtech.jts.algorithm.Area;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.CoordinateList;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.LinearRing;
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.geom.MultiLineString;
import org.locationtech.jts.geom.Point;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.operation.linemerge.LineMerger;
import org.locationtech.jts.operation.overlayng.RingClipper;
import org.locationtech.jts.operation.polygonize.Polygonizer;
import org.rogach.jopenvoronoi.VoronoiDiagram;
import org.rogach.jopenvoronoi.filter.MedialAxisFilter;
import org.rogach.jopenvoronoi.filter.PolygonInteriorFilter;
import org.rogach.jopenvoronoi.geometry.Edge;
import org.rogach.jopenvoronoi.geometry.EdgeType;
import org.rogach.jopenvoronoi.geometry.Face;

/**
 * High-level JTS view of the Voronoi diagram of a JTS geometry.
 * <p>
 * Wraps a {@link VoronoiDiagram} built from any geometry whose elements are
 * points, linestrings, or polygons — including {@link Point},
 * {@link org.locationtech.jts.geom.MultiPoint MultiPoint}, {@link LineString},
 * {@link MultiLineString}, {@link Polygon},
 * {@link org.locationtech.jts.geom.MultiPolygon MultiPolygon}, and
 * heterogeneous {@link org.locationtech.jts.geom.GeometryCollection
 * GeometryCollection}s — and exposes the common derived products directly as
 * JTS geometries:
 * <ul>
 * <li>{@link #getVoronoiEdges()} / {@link #getVoronoiCells()} — the Voronoi
 * diagram as most callers expect it, with each input element treated as a
 * single site and jOpenVoronoi's internal scaffolding stripped</li>
 * <li>{@link #getCells()} — every Voronoi cell in the diagram, one per internal
 * face (well defined for any input, including a pure point set)</li>
 * <li>{@link #getInteriorCells()} — only the cells generated by the polygon
 * interior</li>
 * <li>{@link #getMedialAxis()} — the interior medial axis, dissolved into
 * maximal linestrings</li>
 * <li>{@link #getMedialAxisCoverage()} — the polygonal coverage obtained by
 * cutting the input polygon along its medial axis</li>
 * </ul>
 * The interior and medial-axis products are polygon-specific: for input with no
 * polygonal interior (e.g. a {@link org.locationtech.jts.geom.MultiPoint
 * MultiPoint} or an open {@link LineString}) they return empty results, since
 * no interior or medial axis exists. {@link #getCells()} remains meaningful for
 * every input.
 * <p>
 * Curved (parabolic) Voronoi edges are approximated by adaptively sampled
 * chords whose deviation from the true curve never exceeds the configured
 * tolerance.
 * <p>
 * The Voronoi cells and edges of point and open-lineal input are unbounded and
 * reach the diagram's far boundary. Call {@link #setBoundary(Envelope)} to crop
 * every product to a rectangle; only geometry straddling the rectangle is
 * actually clipped.
 * <p>
 * This object owns the filter state ({@code valid} flags) of its underlying
 * diagram: medial-axis queries reset and re-apply edge filters on each call. If
 * you access {@link #getVoronoiDiagram()} directly and apply your own filters,
 * subsequent medial-axis queries will clear them.
 */
public final class JtsVoronoi {

	/**
	 * Interior-side convention matching the ring orientations produced by
	 * {@link Geometry#norm()}, which {@link JtsGeometryIO} applies to every polygon
	 * before inserting its sites: shells clockwise, holes counter-clockwise, so the
	 * interior lies to the right of each inserted boundary segment.
	 */
	private static final boolean INTERIOR_ON_LEFT = false;

	/**
	 * Fraction of the input envelope diagonal used as the default sampling
	 * tolerance.
	 */
	private static final double DEFAULT_DEVIATION_FRACTION = 1e-3;

	private final Geometry source;
	private final GeometryFactory factory;
	private final double maxDeviation;
	private final VoronoiDiagram diagram;
	private final PolygonInteriorFilter interiorClassifier;

	/**
	 * Optional rectangular crop applied to every returned product, or {@code null}
	 * to return the full (far-boundary-reaching) diagram; see
	 * {@link #setBoundary(Envelope)}.
	 */
	private Envelope boundary;

	/**
	 * Builds the Voronoi diagram of the given geometry with a default geometry
	 * factory and sampling tolerance.
	 * <p>
	 * The default tolerance is {@code 1e-3} of the input envelope diagonal.
	 *
	 * @param geometry a non-empty geometry whose elements are points, linestrings,
	 *                 or polygons (see the class documentation)
	 */
	public JtsVoronoi(Geometry geometry) {
		this(geometry, defaultFactory(geometry), defaultDeviation(geometry));
	}

	/**
	 * Builds the Voronoi diagram of the given geometry.
	 *
	 * @param geometry     a non-empty geometry whose elements are points,
	 *                     linestrings, or polygons (see the class documentation)
	 * @param factory      factory used to build all returned geometries
	 * @param maxDeviation maximum distance the chord approximation of a curved
	 *                     Voronoi edge may deviate from the true curve; must be
	 *                     positive
	 */
	public JtsVoronoi(Geometry geometry, GeometryFactory factory, double maxDeviation) {
		if (geometry == null) {
			throw new IllegalArgumentException("Geometry cannot be null.");
		}
		if (geometry.isEmpty()) {
			throw new IllegalArgumentException("Geometry cannot be empty.");
		}
		if (factory == null) {
			throw new IllegalArgumentException("GeometryFactory cannot be null.");
		}
		if (!(maxDeviation > 0)) {
			throw new IllegalArgumentException("maxDeviation must be positive, got " + maxDeviation);
		}
		this.source = geometry;
		this.factory = factory;
		this.maxDeviation = maxDeviation;
		// Rejects any element that is not a point, linestring, or polygon.
		this.diagram = JtsGeometryIO.toVoronoiDiagram(geometry);
		this.interiorClassifier = new PolygonInteriorFilter(INTERIOR_ON_LEFT);
		this.interiorClassifier.setGraph(diagram.getDiagram());
	}

	private static GeometryFactory defaultFactory(Geometry geometry) {
		return geometry == null ? new GeometryFactory() : geometry.getFactory();
	}

	private static double defaultDeviation(Geometry geometry) {
		if (geometry == null || geometry.isEmpty()) {
			return 1e-6;
		}
		Envelope env = geometry.getEnvelopeInternal();
		double diagonal = Math.hypot(env.getWidth(), env.getHeight());
		return Math.max(diagonal * DEFAULT_DEVIATION_FRACTION, 1e-12);
	}

	/** Returns the input geometry this diagram was built from. */
	public Geometry getSource() {
		return source;
	}

	/** Returns the underlying Voronoi diagram for lower-level access. */
	public VoronoiDiagram getVoronoiDiagram() {
		return diagram;
	}

	// -------------------------------------------------------------------------
	// Boundary crop
	// -------------------------------------------------------------------------

	/**
	 * Sets a rectangular boundary that every product of this object is cropped to,
	 * or clears it.
	 * <p>
	 * When a boundary is set, all cell and line products ({@link #getCells()},
	 * {@link #getInteriorCells()}, {@link #getVoronoiCells()},
	 * {@link #getVoronoiEdges()}, {@link #getMedialAxis()}, and the medial-axis
	 * coverage) are cropped to it: geometry wholly inside is returned unchanged,
	 * geometry wholly outside is dropped, and only geometry straddling the boundary
	 * is actually clipped. This is the intended way to bound the otherwise
	 * unbounded Voronoi cells and edges, which reach the diagram's far boundary.
	 * <p>
	 * Cells are clipped with {@link RingClipper}, a fast Cohen–Sutherland rectangle
	 * clip. For a rectangular crop this is far cheaper than a general overlay, but
	 * it clips each ring independently and does not re-node, so a non-convex cell
	 * that leaves and re-enters the rectangle may yield coincident segments along a
	 * rectangle side; the result is still a usable polygon but not guaranteed
	 * OGC-valid. Point-site cells (always convex) clip exactly.
	 *
	 * @param envelope the crop rectangle; a copy is stored. Passing {@code null} or
	 *                 an empty envelope disables cropping and restores the full
	 *                 diagram.
	 */
	public void setBoundary(Envelope envelope) {
		this.boundary = (envelope == null || envelope.isNull()) ? null : new Envelope(envelope);
	}

	/**
	 * Returns a copy of the current crop boundary, or {@code null} if cropping is
	 * disabled; see {@link #setBoundary(Envelope)}.
	 */
	public Envelope getBoundary() {
		return boundary == null ? null : new Envelope(boundary);
	}

	// -------------------------------------------------------------------------
	// Cells
	// -------------------------------------------------------------------------

	/**
	 * Returns every Voronoi cell in the diagram as a polygon, including the cells
	 * of the polygon exterior (which extend to the diagram's far boundary).
	 * Degenerate faces that do not span a ring are skipped.
	 */
	public List<Polygon> getCells() {
		return cropPolygons(facesToPolygons(diagram.getFaces()));
	}

	/**
	 * Returns the Voronoi cells generated by the polygon interior: the cells of
	 * interior line-site faces and of point-site faces adjacent to them.
	 * <p>
	 * Cell classification is per face, so the point-site cells at convex polygon
	 * corners are included whole even though they straddle the boundary. Intersect
	 * the result with {@link #getSource()} for cells clipped exactly to the input.
	 * <p>
	 * Returns an empty list when the input has no polygonal interior (e.g. a pure
	 * point set or open linework).
	 */
	public List<Polygon> getInteriorCells() {
		List<Face> interior = new ArrayList<>();
		for (Face face : diagram.getFaces()) {
			if (interiorClassifier.isInterior(face)) {
				interior.add(face);
			}
		}
		return cropPolygons(facesToPolygons(interior));
	}

	// -------------------------------------------------------------------------
	// Voronoi diagram (each input element treated as one site)
	// -------------------------------------------------------------------------

	/**
	 * Returns the Voronoi diagram of the input as most callers expect it: the
	 * network of bisector edges separating the cells of the distinct input elements
	 * — points, segments, and polygon boundaries alike — dissolved into maximal
	 * linestrings, with none of jOpenVoronoi's internal scaffolding.
	 * <p>
	 * Two kinds of scaffolding are stripped:
	 * <ul>
	 * <li><b>Per-segment decomposition.</b> jOpenVoronoi splits every inserted
	 * segment into three internal sites (two endpoint point-sites plus a line-site
	 * with a face on each side), so {@link #getCells()} exposes the segment
	 * linework itself ({@link EdgeType#LINESITE}), the endpoint spokes
	 * ({@link EdgeType#SEPARATOR}), and zero-length null edges. All of those are
	 * omitted here.</li>
	 * <li><b>Far-field generators.</b> The diagram is bounded by three seed
	 * point-sites far outside the input; bisectors incident to them are not true
	 * Voronoi edges (they are only where an unbounded cell was artificially
	 * clipped), so an edge is kept only when <em>both</em> of its adjacent cells
	 * belong to real input sites. Genuine unbounded bisectors, which run between
	 * two real cells out to the far boundary, are retained.</li>
	 * </ul>
	 * <p>
	 * Unlike {@link #getMedialAxis()} it applies no polygon-interior filter, so the
	 * result is the complete diagram rather than one restricted to a polygon
	 * interior. Works for point, lineal, polygonal, and mixed input.
	 */
	public MultiLineString getVoronoiEdges() {
		diagram.filterReset();
		List<LineString> lines = new ArrayList<>();
		IdentityHashMap<Edge, Boolean> seenBases = new IdentityHashMap<>();
		for (Edge edge : diagram.getDiagram().edges) {
			if (!isVoronoiEdge(edge)) {
				continue;
			}
			if (edge.base != null && seenBases.put(edge.base, Boolean.TRUE) != null) {
				continue;
			}
			LineString line = toLineString(edge);
			if (line != null) {
				lines.add(line);
			}
		}
		return cropLines(dissolve(lines));
	}

	/**
	 * Returns one Voronoi cell per input site as most callers expect it, treating
	 * each inserted segment (and its endpoints) as a single generator. The
	 * per-segment sub-faces jOpenVoronoi produces (the two line-site half-cells and
	 * the endpoint point-site cells) are merged back into a single polygon, so the
	 * internal decomposition edges seen in {@link #getCells()} are dissolved away.
	 * Standalone point sites yield one cell each. Works for point, lineal,
	 * polygonal, and mixed input.
	 * <p>
	 * Faces are grouped into connected components across {@link EdgeType#LINESITE}
	 * and {@link EdgeType#SEPARATOR} edges: for disjoint segments this yields
	 * exactly one cell per segment. Where linework shares endpoints (a polyline or
	 * ring), the shared endpoint spokes connect the adjacent segments, so a
	 * connected chain is returned as one merged cell.
	 * <p>
	 * The three far-field generator cells are dropped. Genuinely unbounded cells
	 * still reach the diagram's far boundary (and so have very large coordinates);
	 * set a {@link #setBoundary(Envelope) boundary} to crop them to a rectangle. A
	 * cell may carry holes when it entirely encloses another site's cell (e.g. the
	 * cell of a ring around the cell of a point inside it).
	 * <p>
	 * Each merged cell is assembled by tracing the boundary of its face group
	 * directly in the half-edge structure rather than by geometrically unioning the
	 * sub-face polygons: sampled twin half-edges of curved bisectors are not
	 * bit-identical (each twin evaluates the curve through its own
	 * parametrization), so a coverage-style union over sampled sub-faces would
	 * leave slivers along internal curved edges. The topological trace samples
	 * every boundary edge exactly once and never touches internal edges.
	 */
	public List<Polygon> getVoronoiCells() {
		Map<Face, Face> parent = buildSegmentGroups();

		IdentityHashMap<Face, List<Face>> groups = new IdentityHashMap<>();
		for (Face face : diagram.getFaces()) {
			if (isFarFieldFace(face)) {
				continue;
			}
			groups.computeIfAbsent(find(parent, face), k -> new ArrayList<>()).add(face);
		}

		List<Polygon> cells = new ArrayList<>();
		for (Map.Entry<Face, List<Face>> group : groups.entrySet()) {
			Polygon cell = traceCell(parent, group.getKey(), group.getValue());
			if (cell != null) {
				cells.add(cell);
			}
		}
		return cropPolygons(cells);
	}

	/**
	 * Assembles the polygon of one merged cell by tracing the boundary of its face
	 * group in the half-edge structure. A boundary edge is one whose twin face lies
	 * outside the group; boundary edges are stitched into closed rings by following
	 * {@code next} links and hopping across the twins of internal edges. The ring
	 * enclosing the largest area is the shell and any remaining rings are holes.
	 * The zero-area rings traced around the endpoint null-faces collapse under
	 * coordinate deduplication and are dropped.
	 */
	private Polygon traceCell(Map<Face, Face> parent, Face root, List<Face> members) {
		Set<Edge> visited = Collections.newSetFromMap(new IdentityHashMap<>());
		List<LinearRing> rings = new ArrayList<>();
		for (Face face : members) {
			for (Edge edge : face.getEdges()) {
				if (visited.contains(edge) || isInternalEdge(parent, root, edge)) {
					continue;
				}
				LinearRing ring = traceRing(parent, root, edge, visited);
				if (ring != null) {
					rings.add(ring);
				}
			}
		}
		if (rings.isEmpty()) {
			return null;
		}
		LinearRing shell = null;
		double shellArea = -1;
		for (LinearRing ring : rings) {
			double area = Area.ofRing(ring.getCoordinates());
			if (area > shellArea) {
				shellArea = area;
				shell = ring;
			}
		}
		if (rings.size() == 1) {
			return factory.createPolygon(shell);
		}
		List<LinearRing> holes = new ArrayList<>(rings.size() - 1);
		for (LinearRing ring : rings) {
			if (ring != shell) {
				holes.add(ring);
			}
		}
		return factory.createPolygon(shell, holes.toArray(new LinearRing[0]));
	}

	/**
	 * Traces one closed boundary ring starting from the given boundary edge,
	 * marking every traversed edge as visited. Returns {@code null} for degenerate
	 * rings (fewer than three distinct points, e.g. the zero-length null-edge loops
	 * at segment endpoints) or if the walk fails to close.
	 */
	private LinearRing traceRing(Map<Face, Face> parent, Face root, Edge start, Set<Edge> visited) {
		CoordinateList ring = new CoordinateList();
		// The walk visits each boundary half-edge once and hops each internal
		// half-edge at most once, so twice the edge count bounds a well-formed
		// traversal; exceeding it means the structure is malformed.
		int guard = 2 * diagram.getDiagram().edges.size() + 4;
		Edge cur = start;
		do {
			visited.add(cur);
			if (cur.source == null || cur.target == null) {
				return null;
			}
			for (org.rogach.jopenvoronoi.geometry.Point p : cur.samplePoints(maxDeviation)) {
				ring.add(new Coordinate(p.x, p.y), false);
			}
			Edge next = cur.next;
			while (next != null && isInternalEdge(parent, root, next) && guard-- > 0) {
				next = next.twin.next; // hop across the internal edge into the neighboring member face
			}
			cur = next;
		} while (cur != null && cur != start && guard-- > 0);
		if (cur != start) {
			return null;
		}
		ring.closeRing();
		if (ring.size() < 4) {
			return null;
		}
		return factory.createLinearRing(ring.toCoordinateArray());
	}

	/**
	 * Returns whether the edge lies in the interior of the given face group: its
	 * twin's face belongs to the same group, so the edge separates two sub-faces of
	 * one merged cell. Null helper faces and far-field faces are never group
	 * members, so edges against them read as boundary.
	 */
	private boolean isInternalEdge(Map<Face, Face> parent, Face root, Edge edge) {
		Face other = (edge.twin == null) ? null : edge.twin.face;
		return other != null && !other.isNullFace() && find(parent, other) == root;
	}

	/**
	 * Returns whether the edge is a true Voronoi bisector between two real input
	 * sites: a valid, non-scaffolding edge whose two adjacent cells both belong to
	 * real sites (neither a null helper face nor a far-field generator).
	 */
	private boolean isVoronoiEdge(Edge edge) {
		return isMedialAxisEdge(edge) //
				&& isRealSiteFace(edge.face) //
				&& edge.twin != null && isRealSiteFace(edge.twin.face);
	}

	/**
	 * Returns whether the face is a real user-site cell: attached, non-null, with a
	 * generating site, and not one of the far-field bounding generators.
	 */
	private boolean isRealSiteFace(Face face) {
		return face != null && !face.isNullFace() && face.getSite() != null && !isFarFieldFace(face);
	}

	/**
	 * Union-find over the diagram's real faces, joining faces that share a
	 * {@link EdgeType#LINESITE} edge (the two sides of one segment) or a
	 * {@link EdgeType#SEPARATOR} edge (an endpoint cell and its adjacent segment).
	 * Each connected component is one input site.
	 */
	private Map<Face, Face> buildSegmentGroups() {
		IdentityHashMap<Face, Face> parent = new IdentityHashMap<>();
		for (Face face : diagram.getFaces()) {
			parent.put(face, face);
		}
		for (Edge edge : diagram.getDiagram().edges) {
			if (edge == null || edge.twin == null) {
				continue;
			}
			if (edge.type != EdgeType.LINESITE && edge.type != EdgeType.SEPARATOR) {
				continue;
			}
			Face a = edge.face;
			Face b = edge.twin.face;
			if (a == null || b == null || a.isNullFace() || b.isNullFace()) {
				continue;
			}
			union(parent, a, b);
		}
		return parent;
	}

	private static Face find(Map<Face, Face> parent, Face face) {
		parent.putIfAbsent(face, face);
		Face root = face;
		while (parent.get(root) != root) {
			root = parent.get(root);
		}
		while (parent.get(face) != root) {
			Face next = parent.get(face);
			parent.put(face, root);
			face = next;
		}
		return root;
	}

	private static void union(Map<Face, Face> parent, Face a, Face b) {
		Face ra = find(parent, a);
		Face rb = find(parent, b);
		if (ra != rb) {
			parent.put(ra, rb);
		}
	}

	/**
	 * Returns whether the face belongs to one of the three far-field generator
	 * point-sites jOpenVoronoi seeds to bound the diagram. Every real inserted site
	 * lies within the diagram's far radius, so any point-site face at or beyond
	 * that radius is a bounding artifact rather than a user cell.
	 */
	private boolean isFarFieldFace(Face face) {
		if (face == null || face.getSite() == null || !face.getSite().isPoint()) {
			return false;
		}
		org.rogach.jopenvoronoi.geometry.Point p = face.getSite().position();
		return p != null && Math.hypot(p.x, p.y) >= diagram.getFarRadius();
	}

	/**
	 * Crops a list of cell polygons to the {@link #boundary}, or returns it
	 * unchanged when no boundary is set. Polygons wholly inside are passed through,
	 * wholly outside are dropped, and only straddling polygons are clipped.
	 */
	private List<Polygon> cropPolygons(List<Polygon> polygons) {
		if (boundary == null) {
			return polygons;
		}
		RingClipper clipper = new RingClipper(boundary);
		List<Polygon> cropped = new ArrayList<>(polygons.size());
		for (Polygon polygon : polygons) {
			Polygon clipped = clipPolygon(clipper, polygon);
			if (clipped != null && !clipped.isEmpty()) {
				cropped.add(clipped);
			}
		}
		return cropped;
	}

	/**
	 * Clips a single polygon to the boundary rectangle with {@link RingClipper},
	 * short-circuiting on the envelope test so only straddling polygons pay the
	 * clip cost. Each ring is clipped independently; returns {@code null} when the
	 * polygon falls entirely outside the boundary or its shell collapses.
	 */
	private Polygon clipPolygon(RingClipper clipper, Polygon polygon) {
		Envelope pe = polygon.getEnvelopeInternal();
		if (!boundary.intersects(pe)) {
			return null;
		}
		if (boundary.covers(pe)) {
			return polygon;
		}
		LinearRing shell = clipRing(clipper, polygon.getExteriorRing());
		if (shell == null) {
			return null;
		}
		List<LinearRing> holes = new ArrayList<>(polygon.getNumInteriorRing());
		for (int i = 0; i < polygon.getNumInteriorRing(); i++) {
			LinearRing hole = clipRing(clipper, polygon.getInteriorRingN(i));
			if (hole != null) {
				holes.add(hole);
			}
		}
		return factory.createPolygon(shell, holes.toArray(new LinearRing[0]));
	}

	/** Clips one ring; returns {@code null} if it collapses below a valid ring. */
	private LinearRing clipRing(RingClipper clipper, LineString ring) {
		Coordinate[] clipped = clipper.clip(ring.getCoordinates());
		if (clipped.length < 4) {
			return null;
		}
		return factory.createLinearRing(clipped);
	}

	/**
	 * Crops dissolved line products to the {@link #boundary}, or returns them
	 * unchanged when no boundary is set. Lines wholly inside are passed through and
	 * wholly outside are dropped by an envelope test; only straddling lines are
	 * intersected with the rectangle (a general overlay, since {@link RingClipper}
	 * is documented as unsuitable for open linestrings).
	 */
	private MultiLineString cropLines(MultiLineString lines) {
		if (boundary == null) {
			return lines;
		}
		Geometry rectangle = factory.toGeometry(boundary);
		List<LineString> kept = new ArrayList<>(lines.getNumGeometries());
		for (int i = 0; i < lines.getNumGeometries(); i++) {
			LineString line = (LineString) lines.getGeometryN(i);
			Envelope le = line.getEnvelopeInternal();
			if (!boundary.intersects(le)) {
				continue;
			}
			if (boundary.covers(le)) {
				kept.add(line);
				continue;
			}
			collectLines(line.intersection(rectangle), kept);
		}
		return factory.createMultiLineString(kept.toArray(new LineString[0]));
	}

	/** Appends every non-degenerate {@link LineString} component to {@code out}. */
	private static void collectLines(Geometry geometry, List<LineString> out) {
		if (geometry == null || geometry.isEmpty()) {
			return;
		}
		if (geometry instanceof LineString) {
			if (geometry.getLength() > 0) {
				out.add((LineString) geometry);
			}
			return;
		}
		for (int i = 0; i < geometry.getNumGeometries(); i++) {
			collectLines(geometry.getGeometryN(i), out);
		}
	}

	private List<Polygon> facesToPolygons(List<Face> faces) {
		List<Polygon> polygons = new ArrayList<>(faces.size());
		for (Face face : faces) {
			Polygon polygon = toPolygon(face);
			if (polygon != null) {
				polygons.add(polygon);
			}
		}
		return polygons;
	}

	/**
	 * Converts a face to a polygon by walking its half-edge loop and sampling each
	 * edge. Returns {@code null} for degenerate faces.
	 */
	private Polygon toPolygon(Face face) {
		CoordinateList ring = new CoordinateList();
		for (Edge edge : face.getEdges()) {
			if (edge.source == null || edge.target == null) {
				return null;
			}
			for (org.rogach.jopenvoronoi.geometry.Point p : edge.samplePoints(maxDeviation)) {
				ring.add(new Coordinate(p.x, p.y), false);
			}
		}
		ring.closeRing();
		if (ring.size() < 4) {
			return null;
		}
		return factory.createPolygon(ring.toCoordinateArray());
	}

	// -------------------------------------------------------------------------
	// Medial axis
	// -------------------------------------------------------------------------

	/**
	 * Returns the full interior medial axis, dissolved into maximal linestrings.
	 * <p>
	 * The result includes the branches that reach into every convex polygon corner,
	 * which is the mathematically exact medial axis but is often noisy for
	 * downstream use; see {@link #getMedialAxis(double)} to prune low-salience
	 * branches.
	 * <p>
	 * Returns an empty {@link MultiLineString} when the input has no polygonal
	 * interior (e.g. a pure point set or open linework).
	 */
	public MultiLineString getMedialAxis() {
		return cropLines(dissolve(medialAxisLines(Double.NaN)));
	}

	/**
	 * Returns the interior medial axis pruned with a {@link MedialAxisFilter} of
	 * the given aggressiveness, dissolved into maximal linestrings.
	 *
	 * @param aggressiveness pruning aggressiveness in {@code [0,1]}; {@code 0}
	 *                       keeps the full medial axis, {@code 1} prunes maximally
	 */
	public MultiLineString getMedialAxis(double aggressiveness) {
		return cropLines(dissolve(medialAxisLines(aggressiveness)));
	}

	/**
	 * Returns the polygonal coverage obtained by cutting the input polygon along
	 * its full medial axis: every returned polygon is bounded by boundary segments
	 * and medial-axis branches, and together they exactly tile the input.
	 */
	public List<Polygon> getMedialAxisCoverage() {
		return cropPolygons(polygonize(medialAxisLines(Double.NaN)));
	}

	/**
	 * Returns the polygonal coverage obtained by cutting the input polygon along
	 * its medial axis pruned at the given aggressiveness; see
	 * {@link #getMedialAxis(double)}.
	 *
	 * @param aggressiveness pruning aggressiveness in {@code [0,1]}; {@code 0}
	 *                       keeps the full medial axis, {@code 1} prunes maximally
	 */
	public List<Polygon> getMedialAxisCoverage(double aggressiveness) {
		return cropPolygons(polygonize(medialAxisLines(aggressiveness)));
	}

	/**
	 * Collects the interior medial-axis edges as sampled linestrings, resetting and
	 * re-applying the diagram's edge filters.
	 *
	 * @param aggressiveness {@link MedialAxisFilter} aggressiveness, or
	 *                       {@link Double#NaN} for the unpruned axis
	 */
	private List<LineString> medialAxisLines(double aggressiveness) {
		diagram.filterReset();
		diagram.filter(new PolygonInteriorFilter(INTERIOR_ON_LEFT));
		if (!Double.isNaN(aggressiveness)) {
			diagram.filter(new MedialAxisFilter(aggressiveness));
		}

		List<LineString> lines = new ArrayList<>();
		IdentityHashMap<Edge, Boolean> seenBases = new IdentityHashMap<>();
		for (Edge edge : diagram.getDiagram().edges) {
			if (!isMedialAxisEdge(edge)) {
				continue;
			}
			if (edge.base != null && seenBases.put(edge.base, Boolean.TRUE) != null) {
				continue;
			}
			LineString line = toLineString(edge);
			if (line != null) {
				lines.add(line);
			}
		}
		return lines;
	}

	private static boolean isMedialAxisEdge(Edge edge) {
		return edge != null && edge.valid && edge.source != null && edge.target != null //
				&& edge.type != EdgeType.LINESITE //
				&& edge.type != EdgeType.NULLEDGE //
				&& edge.type != EdgeType.OUTEDGE //
				&& edge.type != EdgeType.SEPARATOR;
	}

	/**
	 * Samples an edge into a linestring at {@link #maxDeviation}; returns
	 * {@code null} if degenerate. Curved (parabolic) edges become polylines that
	 * follow the true curve, while straight edges stay two points.
	 */
	private LineString toLineString(Edge edge) {
		CoordinateList coordinates = new CoordinateList();
		for (org.rogach.jopenvoronoi.geometry.Point p : edge.samplePoints(maxDeviation)) {
			coordinates.add(new Coordinate(p.x, p.y), false);
		}
		if (coordinates.size() < 2) {
			return null;
		}
		return factory.createLineString(coordinates.toCoordinateArray());
	}

	/** Merges edge chains at degree-2 nodes into maximal linestrings. */
	private MultiLineString dissolve(List<LineString> lines) {
		LineMerger merger = new LineMerger();
		merger.add(lines);
		@SuppressWarnings("unchecked")
		Collection<LineString> merged = merger.getMergedLineStrings();
		return factory.createMultiLineString(merged.toArray(new LineString[0]));
	}

	/**
	 * Polygonizes the medial-axis lines together with the polygon boundary.
	 * <p>
	 * The boundary linework is taken from the diagram's own line-site edges rather
	 * than from the input geometry, so its coordinates coincide exactly with the
	 * medial-axis branch tips (both are diagram vertex positions) and the
	 * collection is already correctly noded for the polygonizer.
	 */
	private List<Polygon> polygonize(List<LineString> axisLines) {
		Polygonizer polygonizer = new Polygonizer();
		polygonizer.add(axisLines);
		polygonizer.add(boundaryLines());
		@SuppressWarnings("unchecked")
		Collection<Polygon> polygons = polygonizer.getPolygons();
		return new ArrayList<>(polygons);
	}

	/** Returns the inserted boundary segments as linestrings, one per site. */
	private List<LineString> boundaryLines() {
		List<LineString> lines = new ArrayList<>();
		IdentityHashMap<Edge, Boolean> seenBases = new IdentityHashMap<>();
		for (Edge edge : diagram.getDiagram().edges) {
			if (edge == null || edge.type != EdgeType.LINESITE || edge.source == null || edge.target == null) {
				continue;
			}
			if (edge.base != null && seenBases.put(edge.base, Boolean.TRUE) != null) {
				continue;
			}
			lines.add(factory.createLineString(new Coordinate[] { //
					JtsGeometryIO.toCoordinate(edge.source.position), //
					JtsGeometryIO.toCoordinate(edge.target.position) }));
		}
		return lines;
	}
}
